--liquibase formatted sql

--changeset philip:table-creation

CREATE TABLE "PROJECT" (
	"ID" UUID PRIMARY KEY,
	"IDENT" VARCHAR(255) UNIQUE NOT NULL,
	"SUBJECT" TEXT NOT NULL
);

CREATE TABLE "DOCUMENT" (
	"ID" UUID PRIMARY KEY,
	"IDENT" VARCHAR(255) UNIQUE NOT NULL,
	"SUBJECT" TEXT NOT NULL
);

CREATE TABLE "PARAGRAPH" (
	"ID" UUID PRIMARY KEY,
	"SOURCE_ID" UUID, -- Document
	"IDENT" VARCHAR(255) UNIQUE NOT NULL,
	"ORDER" INTEGER NOT NULL,
	"SUBJECT" TEXT NOT NULL
);

CREATE TABLE "REQUIREMENT" (
	"ID" UUID PRIMARY KEY,
	"IDENT" VARCHAR(255) UNIQUE NOT NULL,
	"SUBJECT" TEXT NOT NULL
);

CREATE TABLE "ASSUMPTION" (
	"ID" UUID PRIMARY KEY,
	"IDENT" VARCHAR(255) UNIQUE NOT NULL,
	"SUBJECT" TEXT NOT NULL
);

CREATE TABLE "TESTCASE" (
	"ID" UUID PRIMARY KEY,
	"IDENT" VARCHAR(255) UNIQUE NOT NULL,
	"SUBJECT" TEXT NOT NULL
);

CREATE TABLE "TESTRESULT" (
	"ID" UUID PRIMARY KEY,
	"IDENT" VARCHAR(255) UNIQUE NOT NULL,
	"SUBJECT" TEXT NOT NULL
);

CREATE TABLE "PROJECT_PROJECT" (
	"ID" UUID PRIMARY KEY,
	"SOURCE_ID" UUID, -- Parent
	"TARGET_ID" UUID, -- Child
	"TYPE" INTEGER
);

CREATE TABLE "PROJECT_REQUIREMENT" (
	"ID" UUID PRIMARY KEY,
	"SOURCE_ID" UUID, -- Project
	"TARGET_ID" UUID, -- Requirement
	"TYPE" INTEGER
);

CREATE TABLE "PROJECT_ASSUMPTION" (
	"ID" UUID PRIMARY KEY,
	"SOURCE_ID" UUID, -- Project
	"TARGET_ID" UUID, -- Assumption
	"TYPE" INTEGER
);

CREATE TABLE "PROJECT_TESTCASE" (
	"ID" UUID PRIMARY KEY,
	"SOURCE_ID" UUID, -- Project
	"TARGET_ID" UUID, -- Test Case
	"TYPE" INTEGER
);

CREATE TABLE "PROJECT_TESTRESULT" (
	"ID" UUID PRIMARY KEY,
	"SOURCE_ID" UUID, -- Project
	"TARGET_ID" UUID, -- Test Result
	"TYPE" INTEGER
);

CREATE TABLE "REQUIREMENT_REQUIREMENT" (
	"ID" UUID PRIMARY KEY,
	"SOURCE_ID" UUID, -- Parent
	"TARGET_ID" UUID, -- Child
	"TYPE" INTEGER
);

CREATE TABLE "REQUIREMENT_ASSUMPTION" (
	"ID" UUID PRIMARY KEY,
	"SOURCE_ID" UUID, -- Requirement
	"TARGET_ID" UUID, -- Assumption
	"TYPE" INTEGER
);

CREATE TABLE "REQUIREMENT_TESTCASE" (
	"ID" UUID PRIMARY KEY,
	"SOURCE_ID" UUID, -- Requirement
	"TARGET_ID" UUID, -- Test Case
	"TYPE" INTEGER
);

CREATE TABLE "TESTCASE_TESTCASE" (
	"ID" UUID PRIMARY KEY,
	"SOURCE_ID" UUID, -- Parent
	"TARGET_ID" UUID, -- Child
	"TYPE" INTEGER
);

CREATE TABLE "TESTCASE_TESTRESULT" (
	"ID" UUID PRIMARY KEY,
	"SOURCE_ID" UUID, -- Test Case
	"TARGET_ID" UUID, -- Test Result
	"TYPE" INTEGER
);
