DROP DATABASE IF EXISTS INVDB;
CREATE DATABASE INVDB;
USE INVDB;

CREATE TABLE T_ITEM (
	id UUID PRIMARY KEY DEFAULT(UUID()),
	ident VARCHAR(255) UNIQUE NOT NULL,
	description TEXT
);

CREATE TABLE T_CATEGORY (
	id UUID PRIMARY KEY DEFAULT(UUID()),
	ident VARCHAR(255) UNIQUE NOT NULL,
	description TEXT
);

CREATE TABLE T_PROPERTY (
	id UUID PRIMARY KEY DEFAULT(UUID()),
	ident VARCHAR(255) UNIQUE NOT NULL,
	unit VARCHAR(64) NOT NULL,
	description TEXT
);

CREATE TABLE T_ITEM_CATEGORY (
	id UUID PRIMARY KEY DEFAULT(UUID()),
	item_id UUID NOT NULL,
	category_id UUID NOT NULL,
	CONSTRAINT FK_ITEM_CATEGORY_1 FOREIGN KEY (item_id) REFERENCES T_ITEM(id),
	CONSTRAINT FK_ITEM_CATEGORY_2 FOREIGN KEY (category_id) REFERENCES T_CATEGORY(id)
);

CREATE TABLE T_ITEM_PROPERTY (
	id UUID PRIMARY KEY DEFAULT(UUID()),
	item_id UUID NOT NULL,
	property_id UUID NOT NULL,
	value VARCHAR(255),
	CONSTRAINT FK_ITEM_PROPERTY_1 FOREIGN KEY (item_id) REFERENCES T_ITEM(id),
	CONSTRAINT FK_ITEM_PROPERTY_2 FOREIGN KEY (property_id) REFERENCES T_CATEGORY(id)
);

CREATE TABLE T_NODE (
	id UUID PRIMARY KEY DEFAULT(UUID()),
	parent_id UUID,
	item_id UUID NOT NULL,
	quantity int DEFAULT(1),
	CONSTRAINT FK_NODE_1 FOREIGN KEY (parent_id) REFERENCES T_NODE(id),
	CONSTRAINT FK_NODE_2 FOREIGN KEY (item_id) REFERENCES T_ITEM(id)
);

LOAD DATA LOCAL INFILE './category.csv'
INTO TABLE T_CATEGORY 
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(ident, description);
