#Vaadin Copilot Integration Runtime Properties
#Thu Apr 02 01:31:33 CEST 2026
endpoint=http\://127.0.0.1\:40435/vaadin/copilot-6efe344b-38b9-4442-bc33-e0532f7ca86f
ide=eclipse
supportedActions=write,writeBase64,delete,undo,redo,refresh,showInIde,getModulePaths,compileFiles,restartApplication,getVaadinRoutes,getVaadinVersion,getVaadinComponents,getVaadinEntities,getVaadinSecurity,reloadMavenModule,heartbeat
version=1.0.0
