#Vaadin Copilot Integration Runtime Properties
#Sun Mar 15 21:35:09 CET 2026
endpoint=http\://127.0.0.1\:42547/vaadin/copilot-0665787b-bad1-422b-a93f-e6d9a98962ee
ide=eclipse
supportedActions=write,writeBase64,delete,undo,redo,refresh,showInIde,getModulePaths,compileFiles,restartApplication,getVaadinRoutes,getVaadinVersion,getVaadinComponents,getVaadinEntities,getVaadinSecurity,reloadMavenModule,heartbeat
version=1.0.0
