#Vaadin Copilot Integration Runtime Properties
#Mon Feb 09 23:47:35 CET 2026
endpoint=http\://127.0.0.1\:44979/vaadin/copilot-983ae4fd-4008-433f-ad64-2bbe73e55a77
ide=eclipse
supportedActions=write,writeBase64,delete,undo,redo,refresh,showInIde,getModulePaths,compileFiles,restartApplication,getVaadinRoutes,getVaadinVersion,getVaadinComponents,getVaadinEntities,getVaadinSecurity,reloadMavenModule,heartbeat
version=1.0.0
