#Vaadin Copilot Integration Runtime Properties
#Wed Mar 04 03:05:28 CET 2026
endpoint=http\://127.0.0.1\:46363/vaadin/copilot-4b9d7b7a-f30f-44f9-adfb-ac78d8f2adba
ide=eclipse
supportedActions=write,writeBase64,delete,undo,redo,refresh,showInIde,getModulePaths,compileFiles,restartApplication,getVaadinRoutes,getVaadinVersion,getVaadinComponents,getVaadinEntities,getVaadinSecurity,reloadMavenModule,heartbeat
version=1.0.0
