ui.mainframe.title				EMERGENT GARDEN
ui.mainmenu.app.label			App
ui.mainmenu.app.new.label		New ..
ui.mainmenu.app.open.label		Open ..
ui.mainmenu.app.close.label		Close
ui.mainmenu.app.save.label		Save
ui.mainmenu.app.saveas.label	Save As ..
ui.mainmenu.app.quit.label		Quit
