#Vaadin Copilot Integration Runtime Properties
#Thu Mar 26 22:56:13 CET 2026
endpoint=http\://127.0.0.1\:36475/vaadin/copilot-629312cf-d1b1-4682-9cdd-f604f0ec8cf0
ide=eclipse
supportedActions=write,writeBase64,delete,undo,redo,refresh,showInIde,getModulePaths,compileFiles,restartApplication,getVaadinRoutes,getVaadinVersion,getVaadinComponents,getVaadinEntities,getVaadinSecurity,reloadMavenModule,heartbeat
version=1.0.0
